const worksData = [
	{
		id: "werk1",
		title: "LearninChem",
		role: "VR Developer",
		tools: "Unity 6, C#, Meta quest 3",
		description:
			"LearninChem is een interactieve virtual reality-applicatie die de training in de chemische sector veiliger en efficiënter maakt. Ontwikkeld als een standalone-ervaring voor de Meta Quest-headset. Het systeem is ontworpen als een virtuele faalruimte. Hierin kunnen trainees, zoals jobstudenten en startende laboranten, routinematige labotaken inoefenen. De simulatie is gebouwd in Unity 6 met een functionele low-poly-stijl en begeleidt gebruikers stap voor stap in drie kernmodules. Deze zijn: correct aan doen van persoonlijke beschermingsmiddelen (PBM's), het uitvoeren van een zuur/base-titratie en een geleidbaarheidsmeting. Door deze procedures virtueel te herhalen, bouwen nieuwkomers sneller zelfvertrouwen op. En dan ook zonder enig risico op ongevallen of de verspilling van dure chemicaliën. Dit leertraject verlaagt niet alleen de instapdruk voor nieuw talent, maar verlicht ook de last die ervaren mentoren hebben op de werkvloer.",
		image: "#",
		videoUrl: "https://www.youtube.com/embed/u2scG3Ergtk?si=MzfGm4r5VqYAuvtH",
		gallery: [
			"../Images/LearninChem/Sleutelbeeld_FinalWork_EphramJanssens.jpg",
			"../Images/LearninChem/RoomShot.png",
			"../Images/LearninChem/MainMenu.png",
			"../Images/LearninChem/module1.png",
			"../Images/LearninChem/Module2.png",
			"../Images/LearninChem/Buret.png",
			"../Images/LearninChem/Module3.png",
		],
	},
	{
		id: "werk2",
		title: "Belcatering web app",
		role: "Web developer, photographer, contact person",
		tools: "HTML, CSS, JS, Figma, Illustrator, Photoshop",
		description: "Dit is de uitgebreide uitleg van het project",
		image: "../Images/BelCatering/Belcatering_home.png",
		gallery: [
			"../Images/BelCatering/3d_phone_belcatering.png",
			"../Images/BelCatering/phone_chatbot.png",
			"../Images/BelCatering/phone_example.png",
			"../Images/BelCatering/Belcatering_home.png",
			"../Images/BelCatering/Belcatering_menu_opties.png",
			"../Images/BelCatering/Belcatering_zaalverhuur.png",
			"../Images/BelCatering/Belcatering_kalender.png",
			"../Images/BelCatering/Belcatering_bestel_informatie.png",
			"../Images/BelCatering/Belcatering_bestel_vragen.png",
		],
	},
	{
		id: "werk3",
		title: "Statue pose",
		role: "3D modeller",
		tools: "Unity 6, Maya, Substance painter",
		description: "Dit is de uitgebreide uitleg van het project.",
		image: "#",
		videoUrl: "https://www.youtube.com/embed/x4a-dP9pFh0?si=SvrMieyUx3fZcClw",
		gallery: [
			"../Images/StatuePose/Render1.png",
			"../Images/StatuePose/Render2.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132428.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132448.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132601.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132646.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132742.png",
		],
	},
	{
		id: "werk4",
		title: "Ecosysteem",
		role: "UI/UX Designer",
		tools: "Figma, Illustrator, Photoshop",
		description: "Dit is de uitgebreide uitleg van het project.",
		image: "../Images/Ecosysteem/Kiosk - Start - Finished.png",
		videoUrl: "",
		gallery: [
			"../Images/Ecosysteem/Kiosk - Start - Finished.png",
			"../Images/Ecosysteem/Kiosk - Create - Finished.png",
			"../Images/Ecosysteem/Kiosk - Result - Finished.png",
			"../Images/Ecosysteem/Base - Mobile - Finished.png",
			"../Images/Ecosysteem/Map- Mobile - Finished.png",
			"../Images/Ecosysteem/KioskCreate_wf.png",
			"../Images/Ecosysteem/Mormel.png",
			"../Images/Ecosysteem/KioskResult_wf.png",
			"../Images/Ecosysteem/KioskStart_wf.png",
		],
	},
	{
		id: "werk5",
		title: "Dark patterns",
		role: "3D game developer",
		tools:
			"Unity 6, C#, Vue, Vite, Bootstrap 5, Node.js, Express, PostgreSQL, Docker",
		githubUrl: "https://github.com/EHB-MCT/wdm-EphramJanssens.git",
		description:
			"Real-time analytics platform for Unity games with behavioral tracking and user profiling. This project offers a full-stack solution for collecting, storing, and visualizing gameplay data. The system connects a Unity game with a Node.js backend and a Vue 3 frontend dashboard to provide insight into player behavior through detailed logs and statistics.",
		image: "../Images/Dark patterns/1.png",
		videoUrl: "",
		gallery: [
			"../Images/Dark patterns/1.png",
			"../Images/Dark patterns/2.png",
			"../Images/Dark patterns/3.png",
			"../Images/Dark patterns/4.png",
		],
	},
];
