const worksData = [
	{
		id: "werk1",
		title: "LearninChem",
		role: "VR Developer",
		tools: "Unity 6, C#, Meta quest 3",
		githubUrl: "https://github.com/EphramJanssens/LearninChem.git",
		description:
			"LearninChem is een interactieve virtual reality-applicatie die de training in de chemische sector veiliger en efficiënter maakt. Ontwikkeld als een standalone-ervaring voor de Meta Quest-headset. Het systeem is ontworpen als een virtuele faalruimte. Hierin kunnen trainees, zoals jobstudenten en startende laboranten, routinematige labotaken inoefenen. De simulatie is gebouwd in Unity 6 met een functionele low-poly-stijl en begeleidt gebruikers stap voor stap in drie kernmodules. Deze zijn: correct aan doen van persoonlijke beschermingsmiddelen (PBM's), het uitvoeren van een zuur/base-titratie en een geleidbaarheidsmeting. Door deze procedures virtueel te herhalen, bouwen nieuwkomers sneller zelfvertrouwen op. En dan ook zonder enig risico op ongevallen of de verspilling van dure chemicaliën. Dit leertraject verlaagt niet alleen de instapdruk voor nieuw talent, maar verlicht ook de last die ervaren mentoren hebben op de werkvloer.",
		image: "#",
		videoUrl: "https://www.youtube.com/embed/u2scG3Ergtk?si=MzfGm4r5VqYAuvtH",
		gallery: [
			"../Images/LearninChem/Sleutelbeeld_FinalWork_EphramJanssens.jpg",
			"../Images/LearninChem/RoomShot.png",
			"../Images/LearninChem/MainMenu.png",
			"../Images/LearninChem/module1.png",
			"../Images/LearninChem/Module2.png",
			"../Images/LearninChem/Buret.png",
			"../Images/LearninChem/Module3.png",
		],
	},
	{
		id: "werk2",
		title: "Belcatering web app",
		role: "Web developer, photographer, contact person",
		tools: "HTML, CSS, JS, Figma, Illustrator, Photoshop",
		description:
			"Dit volledige project is gemaakt voor een cateringbedrijf genaamd Belcatering. Zij gebruiken lokale producten en mensen om eten te bereiden en hun bedrijf te runnen. Dit project is uitgevoerd door een team van 6 studenten.",
		image: "../Images/BelCatering/Belcatering_home.png",
		gallery: [
			"../Images/BelCatering/3d_phone_belcatering.png",
			"../Images/BelCatering/phone_chatbot.png",
			"../Images/BelCatering/phone_example.png",
			"../Images/BelCatering/Belcatering_home.png",
			"../Images/BelCatering/Belcatering_menu_opties.png",
			"../Images/BelCatering/Belcatering_zaalverhuur.png",
			"../Images/BelCatering/Belcatering_kalender.png",
			"../Images/BelCatering/Belcatering_bestel_informatie.png",
			"../Images/BelCatering/Belcatering_bestel_vragen.png",
		],
	},
	{
		id: "werk3",
		title: "Statue pose",
		role: "3D modeller",
		tools: "Unity 6, Maya, Substance painter",
		description:
			"Een opdracht voor 3D. Het doel van deze oprdacht was om de 3D modelling pipeline van Maya naar Unity 6 te gebruiken. Hier leerde ik Substance Painter en animation in Maya.",
		image: "#",
		videoUrl: "https://www.youtube.com/embed/x4a-dP9pFh0?si=SvrMieyUx3fZcClw",
		gallery: [
			"../Images/StatuePose/Render1.png",
			"../Images/StatuePose/Render2.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132428.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132448.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132601.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132646.png",
			"../Images/StatuePose/Screenshot 2025-09-23 132742.png",
		],
	},
	{
		id: "werk4",
		title: "Ecosysteem",
		role: "UI/UX Designer",
		tools: "Figma, Illustrator, Photoshop",
		description: "Dit is de uitgebreide uitleg van het project.",
		image: "../Images/Ecosysteem/Kiosk - Start - Finished.png",
		videoUrl: "",
		gallery: [
			"../Images/Ecosysteem/Kiosk - Start - Finished.png",
			"../Images/Ecosysteem/Kiosk - Create - Finished.png",
			"../Images/Ecosysteem/Kiosk - Result - Finished.png",
			"../Images/Ecosysteem/Base - Mobile - Finished.png",
			"../Images/Ecosysteem/Map- Mobile - Finished.png",
			"../Images/Ecosysteem/KioskCreate_wf.png",
			"../Images/Ecosysteem/Mormel.png",
			"../Images/Ecosysteem/KioskResult_wf.png",
			"../Images/Ecosysteem/KioskStart_wf.png",
			"../Images/Ecosysteem/Stijlgids.png",
		],
	},
	{
		id: "werk5",
		title: "Dark patterns",
		role: "3D game developer",
		tools:
			"Unity 6, C#, Vue, Vite, Bootstrap 5, Node.js, Express, PostgreSQL, Docker",
		githubUrl: "https://github.com/EHB-MCT/wdm-EphramJanssens.git",
		description:
			"Realtime analyseplatform voor Unity-games met gedragsregistratie en gebruikersprofiling. Dit project biedt een complete oplossing voor het verzamelen, opslaan en visualiseren van gameplaydata. Het systeem verbindt een Unity-game met een Node.js-backend en een Vue 3-frontenddashboard om inzicht te geven in spelersgedrag via gedetailleerde logboeken en statistieken.",
		image: "../Images/Dark patterns/1.png",
		videoUrl: "",
		gallery: [
			"../Images/Dark patterns/1.png",
			"../Images/Dark patterns/2.png",
			"../Images/Dark patterns/3.png",
			"../Images/Dark patterns/4.png",
		],
	},
	{
		id: "werk6",
		title: "Finaly festival time",
		role: "UI/UX designer",
		tools: "Figma, Illustrator, Photoshop",
		githubUrl: "",
		description:
			"Finaly festival time was een opdracht voor het vak Design 2. We moesten zelf een fictieve festival creëren en UX/UI voor maken. Dit was mijn eerste poging UX/UI design.",
		image: "../Images/FinalyFestivalTime/logo_MetalFest_Ephram_Janssens.png",
		videoUrl: "",
		gallery: [
			"../Images/FinalyFestivalTime/logo_MetalFest_Ephram_Janssens.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_1.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_2.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_3.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_4.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_5.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_6.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_7.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_8.png",
			"../Images/FinalyFestivalTime/Ephram_Janssens_festival_Page_9.png",
			"../Images/FinalyFestivalTime/Concept_Ephram_Janssens.png",
		],
	},
	{
		id: "werk7",
		title: "PowerBack",
		role: "Designer",
		tools: "Illustrator, Photoshop, Indesign",
		githubUrl: "",
		description:
			"PowerBack was een opdracht voor Design 3. De opdracht was om rond een fictief product reclame te maken. Hieronder vind u de poster, teaser en instagram carrousel.",
		image: "../Images/PowerBack/Poster_ephram_Janssens.png",
		videoUrl: "",
		gallery: [
			"../Images/PowerBack/Poster_ephram_Janssens.png",
			"../Images/PowerBack/Teaser_Ephram_Janssens.png",
			"../Images/PowerBack/Insta_carrousel_Ephram_Janssens_carrousel 1.png",
			"../Images/PowerBack/Insta_carrousel_Ephram_Janssens_carrousel 2.png",
			"../Images/PowerBack/Insta_carrousel_Ephram_Janssens_carrousel 3.png",
		],
	},
	{
		id: "werk8",
		title: "Opdracht 3D games",
		role: "3D game developer",
		tools: "Unity 6, C#",
		githubUrl: "",
		description:
			"Deze opdracht was mijn eerste werkende game. Dit is een horror game waar de speler puzzels moet oplossen om op tijd naar de volgende kamer te ontsnappen. Deze opdracht was gemaakt met 1 medestudent.",
		image: "../Images/3DGames/Screenshot 2025-11-03 140447.png",
		videoUrl: "",
		gallery: [
			"../Images/3DGames/Screenshot 2025-11-03 140447.png",
			"../Images/3DGames/Screenshot 2025-11-03 140527.png",
			"../Images/3DGames/Screenshot 2025-11-03 140609.png",
			"../Images/3DGames/Screenshot 2025-11-03 140719.png",
			"../Images/3DGames/Screenshot 2025-11-03 140817.png",
			"../Images/3DGames/Screenshot 2025-11-03 150316.png",
			"../Images/3DGames/Screenshot 2025-11-03 150417.png",
			"../Images/3DGames/Screenshot 2025-11-03 150442.png",
		],
	},
];
